services:

  db:
    restart: "no"
    ports:
      - "5432:5432"

  redis:
    restart: "no"
    ports:
      - "6379:6379"

  minio:
    restart: "no"
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: backend/Dockerfile
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./backend/htmlcov:/app/backend/htmlcov
    environment:
      SMTP_HOST: "mailcatcher"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  frontend:
    restart: "no"
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    develop:
      watch:
        - path: ./frontend
          action: sync
          target: /app/frontend
          ignore:
            - ./frontend/node_modules
            - ./frontend/.next
        - path: ./frontend/package.json
          action: rebuild
        - path: ./bun.lock
          action: rebuild

networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false
