// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, PermissionsReadPermissionsData, PermissionsReadPermissionsResponse, PermissionsReadPermissionData, PermissionsReadPermissionResponse, PrivateCreateUserData, PrivateCreateUserResponse, RbacReadUserPermissionsData, RbacReadUserPermissionsResponse, RbacAssignRoleData, RbacAssignRoleResponse, RbacRemoveRoleData, RbacRemoveRoleResponse, RbacReadRolePermissionsData, RbacReadRolePermissionsResponse, RbacAddPermissionData, RbacAddPermissionResponse, RbacRemovePermissionData, RbacRemovePermissionResponse, RolesReadRolesData, RolesReadRolesResponse, RolesReadRoleData, RolesReadRoleResponse, TenantsReadTenantsData, TenantsReadTenantsResponse, TenantsReadTenantData, TenantsReadTenantResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class ItemsService {
    /**
     * Read Items
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Create Item
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Read Item
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Update Item
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Delete Item
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
}

export class PermissionsService {
    /**
     * Read Permissions
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns PermissionsPublic Successful Response
     * @throws ApiError
     */
    public static readPermissions(data: PermissionsReadPermissionsData = {}): CancelablePromise<PermissionsReadPermissionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/permissions/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Read Permission
     * @param data The data for the request.
     * @param data.permissionId
     * @returns PermissionPublic Successful Response
     * @throws ApiError
     */
    public static readPermission(data: PermissionsReadPermissionData): CancelablePromise<PermissionsReadPermissionResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/permissions/{permission_id}',
            path: {
                permission_id: data.permissionId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
}

export class RbacService {
    /**
     * Read User Permissions
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPermissions Successful Response
     * @throws ApiError
     */
    public static readUserPermissions(data: RbacReadUserPermissionsData): CancelablePromise<RbacReadUserPermissionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rbac/users/{user_id}/permissions',
            path: {
                user_id: data.userId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Assign Role
     * @param data The data for the request.
     * @param data.userId
     * @param data.roleId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static assignRole(data: RbacAssignRoleData): CancelablePromise<RbacAssignRoleResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/rbac/users/{user_id}/roles/{role_id}',
            path: {
                user_id: data.userId,
                role_id: data.roleId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Remove Role
     * @param data The data for the request.
     * @param data.userId
     * @param data.roleId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static removeRole(data: RbacRemoveRoleData): CancelablePromise<RbacRemoveRoleResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/rbac/users/{user_id}/roles/{role_id}',
            path: {
                user_id: data.userId,
                role_id: data.roleId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Read Role Permissions
     * @param data The data for the request.
     * @param data.roleId
     * @returns RolePermissionsPublic Successful Response
     * @throws ApiError
     */
    public static readRolePermissions(data: RbacReadRolePermissionsData): CancelablePromise<RbacReadRolePermissionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rbac/roles/{role_id}/permissions',
            path: {
                role_id: data.roleId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Add Permission
     * @param data The data for the request.
     * @param data.roleId
     * @param data.permissionId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static addPermission(data: RbacAddPermissionData): CancelablePromise<RbacAddPermissionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/rbac/roles/{role_id}/permissions/{permission_id}',
            path: {
                role_id: data.roleId,
                permission_id: data.permissionId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Remove Permission
     * @param data The data for the request.
     * @param data.roleId
     * @param data.permissionId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static removePermission(data: RbacRemovePermissionData): CancelablePromise<RbacRemovePermissionResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/rbac/roles/{role_id}/permissions/{permission_id}',
            path: {
                role_id: data.roleId,
                permission_id: data.permissionId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
}

export class RolesService {
    /**
     * Read Roles
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns RolesPublic Successful Response
     * @throws ApiError
     */
    public static readRoles(data: RolesReadRolesData = {}): CancelablePromise<RolesReadRolesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/roles/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Read Role
     * @param data The data for the request.
     * @param data.roleId
     * @returns RolePublic Successful Response
     * @throws ApiError
     */
    public static readRole(data: RolesReadRoleData): CancelablePromise<RolesReadRoleResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/roles/{role_id}',
            path: {
                role_id: data.roleId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
}

export class TenantsService {
    /**
     * Read Tenants
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns TenantsPublic Successful Response
     * @throws ApiError
     */
    public static readTenants(data: TenantsReadTenantsData = {}): CancelablePromise<TenantsReadTenantsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/tenants/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Read Tenant
     * @param data The data for the request.
     * @param data.tenantId
     * @returns TenantPublic Successful Response
     * @throws ApiError
     */
    public static readTenant(data: TenantsReadTenantData): CancelablePromise<TenantsReadTenantResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/tenants/{tenant_id}',
            path: {
                tenant_id: data.tenantId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Create User
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Read User Me
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me',
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Delete User Me
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me',
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Update User Me
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Update User
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Delete User
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/',
            errors: {
                '4XX': 'Client Error'
            }
        });
    }
}