// This file is auto-generated by @hey-api/openapi-ts

/**
 * One audit row as returned over the API.
 *
 * ``before``/``after`` are the snapshots captured at write time via
 * ``audit.snapshot``, which is an explicit non-secret allow-list — so they
 * carry no credentials or connection secrets (MCP/tool ``config`` is never
 * captured) and are safe to expose to an ``audit:read`` holder.
 */
export type AuditLogPublic = {
    id: string;
    actor_id: (string | null);
    action: string;
    target_type: string;
    target_id: (string | null);
    before: ({
    [key: string]: unknown;
} | null);
    after: ({
    [key: string]: unknown;
} | null);
    created_at: string;
};

export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

/**
 * Standard error envelope returned by all API error responses.
 */
export type ErrorResponse = {
    code: string;
    message: string;
    details?: (unknown | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type PermissionPublic = {
    id: string;
    name: string;
    resource: string;
    action: string;
    description?: (string | null);
    created_at?: (string | null);
};

export type PermissionsPublic = {
    data: Array<PermissionPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RolePermissionsPublic = {
    data: Array<PermissionPublic>;
    count: number;
};

export type RolePublic = {
    id: string;
    name: string;
    description?: (string | null);
    created_at?: (string | null);
};

export type RolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type TenantPublic = {
    id: string;
    name: string;
    slug: string;
    is_active: boolean;
    created_at?: (string | null);
};

export type TenantsPublic = {
    data: Array<TenantPublic>;
    count: number;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
};

/**
 * A user's effective roles and the permissions they grant.
 */
export type UserPermissions = {
    roles: Array<RolePublic>;
    permissions: Array<PermissionPublic>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    tenant_id: string;
    created_at?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type AuditReadAuditLogsData = {
    limit?: number;
    skip?: number;
};

export type AuditReadAuditLogsResponse = (AuditLogsPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type PermissionsReadPermissionsData = {
    limit?: number;
    skip?: number;
};

export type PermissionsReadPermissionsResponse = (PermissionsPublic);

export type PermissionsReadPermissionData = {
    permissionId: string;
};

export type PermissionsReadPermissionResponse = (PermissionPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RbacReadUserPermissionsData = {
    userId: string;
};

export type RbacReadUserPermissionsResponse = (UserPermissions);

export type RbacAssignRoleData = {
    roleId: string;
    userId: string;
};

export type RbacAssignRoleResponse = (Message);

export type RbacRemoveRoleData = {
    roleId: string;
    userId: string;
};

export type RbacRemoveRoleResponse = (Message);

export type RbacReadRolePermissionsData = {
    roleId: string;
};

export type RbacReadRolePermissionsResponse = (RolePermissionsPublic);

export type RbacAddPermissionData = {
    permissionId: string;
    roleId: string;
};

export type RbacAddPermissionResponse = (Message);

export type RbacRemovePermissionData = {
    permissionId: string;
    roleId: string;
};

export type RbacRemovePermissionResponse = (Message);

export type RolesReadRolesData = {
    limit?: number;
    skip?: number;
};

export type RolesReadRolesResponse = (RolesPublic);

export type RolesReadRoleData = {
    roleId: string;
};

export type RolesReadRoleResponse = (RolePublic);

export type TenantsReadTenantsData = {
    limit?: number;
    skip?: number;
};

export type TenantsReadTenantsResponse = (TenantsPublic);

export type TenantsReadTenantData = {
    tenantId: string;
};

export type TenantsReadTenantResponse = (TenantPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersExportMyDataResponse = ({
    [key: string]: unknown;
});

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersExportUserDataData = {
    userId: string;
};

export type UsersExportUserDataResponse = ({
    [key: string]: unknown;
});

export type UsersEraseUserDataData = {
    userId: string;
};

export type UsersEraseUserDataResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);