"""Tenant scoping on user-facing tables + create AI/OCR tables

Hand-written (not autogenerated): the AI/OCR tables existed only as SQLModel
classes with no prior revision, so autogenerate against a migrated DB is
unreliable. No deployed environment has these tables, hence plain
``create_table`` (no inspector guards).

Revision ID: b7d4e12a9f03
Revises: a7c3f1e92b10
Create Date: 2026-07-12 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = 'b7d4e12a9f03'
down_revision = 'a7c3f1e92b10'
branch_labels = None
depends_on = None

# Fixed bootstrap tenant id — keep in sync with
# app.modules.iam.tenants.seed.DEFAULT_TENANT_ID.
DEFAULT_TENANT_ID = '00000000-0000-4000-8000-000000000001'


def upgrade():
    # --- 1. Bootstrap the default tenant (idempotent on slug).
    op.execute(
        "INSERT INTO tenant (id, name, slug, is_active, created_at) "
        f"VALUES ('{DEFAULT_TENANT_ID}', 'Default', 'default', true, now()) "
        "ON CONFLICT (slug) DO NOTHING"
    )

    # --- 2. AI tables (previously model-only; global catalogs stay
    # tenant-free per ADR-0006).
    op.create_table(
        'agent',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('config', JSONB(), server_default='{}', nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_agent_name'), 'agent', ['name'], unique=True)

    op.create_table(
        'tool',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('tool_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column('config', JSONB(), server_default='{}', nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_tool_name'), 'tool', ['name'], unique=True)

    op.create_table(
        'mcpserver',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column('config', JSONB(), server_default='{}', nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_mcpserver_name'), 'mcpserver', ['name'], unique=True)

    op.create_table(
        'agenttool',
        sa.Column('agent_id', sa.Uuid(), nullable=False),
        sa.Column('tool_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('agent_id', 'tool_id'),
    )

    # Conversation is tenant-scoped from birth: NOT NULL + CASCADE.
    op.create_table(
        'conversation',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('agent_id', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_conversation_tenant_id'), 'conversation', ['tenant_id'], unique=False
    )

    op.create_table(
        'message',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('conversation_id', sa.Uuid(), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('metadata', JSONB(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['conversation_id'], ['conversation.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )

    # --- 3. OCR table (previously model-only), tenant-scoped from birth.
    op.create_table(
        'ocr_document',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('file_size_bytes', sa.Integer(), nullable=False),
        sa.Column('page_count', sa.Integer(), nullable=True),
        sa.Column('minio_key', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('extracted_text', sa.Text(), nullable=True),
        sa.Column('provider_used', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column('processing_time_ms', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_ocr_document_tenant_id'), 'ocr_document', ['tenant_id'], unique=False
    )

    # --- 4. Tenant-scope the existing tables: add nullable, backfill to the
    # default tenant, then tighten to NOT NULL + FK + index.
    op.add_column('user', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.execute(
        "UPDATE \"user\" SET tenant_id = "
        "(SELECT id FROM tenant WHERE slug = 'default') WHERE tenant_id IS NULL"
    )
    op.alter_column('user', 'tenant_id', nullable=False)
    op.create_foreign_key(
        'fk_user_tenant_id_tenant', 'user', 'tenant',
        ['tenant_id'], ['id'], ondelete='RESTRICT',
    )
    op.create_index(op.f('ix_user_tenant_id'), 'user', ['tenant_id'], unique=False)

    op.add_column('item', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.execute(
        "UPDATE item SET tenant_id = "
        "(SELECT id FROM tenant WHERE slug = 'default') WHERE tenant_id IS NULL"
    )
    op.alter_column('item', 'tenant_id', nullable=False)
    op.create_foreign_key(
        'fk_item_tenant_id_tenant', 'item', 'tenant',
        ['tenant_id'], ['id'], ondelete='CASCADE',
    )
    op.create_index(op.f('ix_item_tenant_id'), 'item', ['tenant_id'], unique=False)


def downgrade():
    op.drop_index(op.f('ix_item_tenant_id'), table_name='item')
    op.drop_constraint('fk_item_tenant_id_tenant', 'item', type_='foreignkey')
    op.drop_column('item', 'tenant_id')

    op.drop_index(op.f('ix_user_tenant_id'), table_name='user')
    op.drop_constraint('fk_user_tenant_id_tenant', 'user', type_='foreignkey')
    op.drop_column('user', 'tenant_id')

    op.drop_index(op.f('ix_ocr_document_tenant_id'), table_name='ocr_document')
    op.drop_table('ocr_document')
    op.drop_table('message')
    op.drop_index(op.f('ix_conversation_tenant_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_table('agenttool')
    op.drop_index(op.f('ix_mcpserver_name'), table_name='mcpserver')
    op.drop_table('mcpserver')
    op.drop_index(op.f('ix_tool_name'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_agent_name'), table_name='agent')
    op.drop_table('agent')

    # Remove only the bootstrap row this migration inserted.
    op.execute(f"DELETE FROM tenant WHERE id = '{DEFAULT_TENANT_ID}'")
