"""soft-delete deleted_at + append-only audit log

Revision ID: b952011f1fff
Revises: df276405dedc
Create Date: 2026-09-04 07:34:12.545765

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b952011f1fff'
down_revision = 'df276405dedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_actor_id'), 'auditlog', ['actor_id'], unique=False)
    op.create_index(op.f('ix_auditlog_target_id'), 'auditlog', ['target_id'], unique=False)
    op.create_index(op.f('ix_auditlog_target_type'), 'auditlog', ['target_type'], unique=False)
    op.add_column('item', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_item_deleted_at'), 'item', ['deleted_at'], unique=False)
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_column('user', 'deleted_at')
    op.drop_index(op.f('ix_item_deleted_at'), table_name='item')
    op.drop_column('item', 'deleted_at')
    op.drop_index(op.f('ix_auditlog_target_type'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_target_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_actor_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
